package ca.aversa.insessionservice.exception

class RegisterUserException(cause: Throwable? = null): RuntimeException(cause) {
}